language: rust

rust:
  - 1.18.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

sudo: false

cache: cargo

install:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then rustup component add rustfmt-preview; fi

script:
  - if [ $TRAVIS_RUST_VERSION = "stable" ]; then cargo fmt --all -- --check; fi
  - cargo build --verbose
  - cargo test --verbose
